// src/routes/writing/index.svelte
<script context="module">
  import query from './query'
  import gqlr from '$lib/utils/gql-request'

  export async function load() {
    const { allWritings } = await gqlr(query)
    return { props: { allWritings } }
  }
</script>

<script>
  import ProjectInfoCard from '$lib/components/project-info-card/index.svelte'

  export let allWritings
</script>

<div class="writing">
  <h1>(Sick animation to create the title)</h1>
  <p>And heeeere they are:</p>
  {#each allWritings as writing (writing.title)}
    <ProjectInfoCard {...writing} />
  {/each}
</div>

// pages/writing/index.jsx
import s from './style.module.css'
import fetchFromCms from '../../lib/cmsClient'
import query from './query.graphql'
import ProjectInfoCard from '../../components/project-info-card'

function WritingPage({ allWritings }) {
  return (
    <div className={s.writing}>
      <h1>Writing</h1>
      <p>And heeeere they are:</p>
      {allWritings.map((writing) => (
        <ProjectInfoCard key={writing.title} {...writing} />
      ))}
    </div>
  )
}

export async function getStaticProps() {
  const { allWritings } = await fetchFromCms(query)

  return {
    props: {
      allWritings
    }
  }
}

export default WritingPage
