// pages/writing/index.jsx
import s from './style.module.css'
import fetchFromCms from '../../lib/cmsClient'
import query from './query.graphql'
import ProjectInfoCard from '../../components/project-info-card'

function WritingPage({ allWritings }) {
  return (
    <div className={s.writing}>
      <h1>Writing</h1>
      <p>And heeeere they are:</p>
      {allWritings.map((writing) => (
        <ProjectInfoCard key={writing.title} {...writing} />
      ))}
    </div>
  )
}

export async function getStaticProps() {
  const { allWritings } = await fetchFromCms(query)

  return {
    props: {
      allWritings
    }
  }
}

export default WritingPage

// src/routes/_(main-pages)/writing/+page.svelte
<script lang="ts">
	import ProjectInfoCard from '$lib/components/project-info-card/index.svelte'

	interface WritingPageProps {
		writings: any
	}

	export let data
	let { writings }: WritingPageProps = data
</script>

<h1>(Sick animation to create the title)</h1>
<p>And heeeere they are:</p>
{#each writings as writing (writing.title)}
	<ProjectInfoCard {...writing} />
{/each}
<p>Let's test out some <a href="#0">links</a></p>
