// src/routes/_(main-pages)/websites/+page.svelte
<script lang="ts">
	import ProjectInfoCard from '$lib/components/project-info-card/index.svelte'

	interface WebsitePageProps {
		websites: any
	}

	export let data
	let { websites }: WebsitePageProps = data
</script>

<h1>(Sick animation to create the title)</h1>
<p>And heeeere they are:</p>
{#each websites as website (website.title)}
	<ProjectInfoCard {...website} />
{/each}
<p>Let's test out some <a href="#0">links</a></p>

// old-next/pages/websites/index.jsx
import s from './style.module.css'
import fetchFromCms from '../../lib/cmsClient'
import query from './query.graphql'
import ProjectInfoCard from '../../components/project-info-card'

function WebsitesPage({ allWebsites }) {
  return (
    <div className={s.websites}>
      <h1>Websites</h1>
      <p>And heeeere they are:</p>
      {allWebsites.map((website) => (
        <ProjectInfoCard key={website.title} {...website} />
      ))}
    </div>
  )
}

export async function getStaticProps() {
  const { allWebsites } = await fetchFromCms(query)

  return {
    props: {
      allWebsites
    }
  }
}

export default WebsitesPage
