// old-next/pages/games/index.jsx
import s from './style.module.css'
import fetchFromCms from '../../lib/cmsClient'
import query from './query.graphql'
import ProjectInfoCard from '../../components/project-info-card'

function GamesPage({ allGames }) {
  return (
    <div className={s.games}>
      <h1>Games</h1>
      <p>And heeeere they are:</p>
      {allGames.map((game) => (
        <ProjectInfoCard key={game.title} {...game} />
      ))}
    </div>
  )
}

export async function getStaticProps() {
  const { allGames } = await fetchFromCms(query)

  return {
    props: {
      allGames
    }
  }
}

export default GamesPage

// src/routes/_(main-pages)/games/+page.svelte
<script lang="ts">
	import ProjectInfoCard from '$lib/components/project-info-card/index.svelte'

	interface GamePageProps {
		games: any
	}

	export let data
	let { games }: GamePageProps = data
</script>

<h1>(Sick animation to create the title)</h1>
<p>And heeeere they are:</p>
{#each games as game (game.title)}
	<ProjectInfoCard {...game} />
{/each}
