// pages/audio/index.jsx
import s from './style.module.css'
import fetchFromCms from '../../lib/cmsClient'
import query from './query.graphql'
import ProjectInfoCard from '../../components/project-info-card'

function AudioPage({ allAudios }) {
  return (
    <div className={s.audio}>
      <h1>Audio</h1>
      <p>And heeeere they are:</p>
      {allAudios.map((audio) => (
        <ProjectInfoCard key={audio.title} {...audio} />
      ))}
    </div>
  )
}

export async function getStaticProps() {
  const { allAudios } = await fetchFromCms(query)

  return {
    props: {
      allAudios
    }
  }
}

export default AudioPage

// site/src/routes/audio/index.svelte
<script context="module">
  import query from './query'
  import gqlr from '$lib/utils/gql-request'

  export async function load() {
    const { allAudios } = await gqlr(query)
    return { props: { allAudios } }
  }
</script>

<script>
  import ProjectInfoCard from '$lib/components/project-info-card/index.svelte'

  export let allAudios
</script>

<div class="audio">
  <h1>(Sick animation to create the title)</h1>
  <p>And heeeere they are:</p>

  {#each allAudios as audio (audio.title)}
    <ProjectInfoCard {...audio} />
  {/each}
</div>
