// old-next/pages/games/index.jsx
import s from './style.module.css'
import fetchFromCms from '../../lib/cmsClient'
import query from './query.graphql'
import ProjectInfoCard from '../../components/project-info-card'

function GamesPage({ allGames }) {
  return (
    <div className={s.games}>
      <h1>Games</h1>
      <p>And heeeere they are:</p>
      {allGames.map((game) => (
        <ProjectInfoCard key={game.title} {...game} />
      ))}
    </div>
  )
}

export async function getStaticProps() {
  const { allGames } = await fetchFromCms(query)

  return {
    props: {
      allGames
    }
  }
}

export default GamesPage

// src/routes/games/index.svelte
<script context="module">
  import query from './query'
  import gqlr from '$lib/utils/gql-request'

  export async function load() {
    const { allGames } = await gqlr(query)
    return { props: { allGames } }
  }
</script>

<script>
  import ProjectInfoCard from '$lib/components/project-info-card/index.svelte'

  export let allGames
</script>

<div class="games">
  <h1>(Sick animation to create the title)</h1>
  <p>And heeeere they are:</p>
  {#each allGames as game (game.title)}
    <ProjectInfoCard {...game} />
  {/each}
</div>
